//===================================================================
// COPYRIGHT  2022/03/08
//===================================================================
// CAAPartDesignCommand.cpp
// Header definition of class CAAPartDesignCommand
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2022/03/08 Creation: Code generated by the 3DS wizard
//===================================================================
#ifndef ExportedByCAAPartDesignCommand_H
#define ExportedByCAAPartDesignCommand_H
#if defined(__CAAPartDesignCommand)
# define ExportedByCAAPartDesignCommand   DSYExport
#else // __CAAPartDesignCommand
# define ExportedByCAAPartDesignCommand   DSYImport
#endif  // __CAAPartDesignCommand
#include "DSYExport.h"
#endif //ExportedByCAAPartDesignCommand_H

