//===================================================================
// COPYRIGHT  2022/03/08
//===================================================================
// TestModuleCommand.cpp
// Header definition of class TestModuleCommand
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2022/03/08 Creation: Code generated by the 3DS wizard
//===================================================================
#ifndef ExportedByTestModuleCommand_H
#define ExportedByTestModuleCommand_H
#if defined(__TestModuleCommand)
# define ExportedByTestModuleCommand   DSYExport
#else // __TestModuleCommand
# define ExportedByTestModuleCommand   DSYImport
#endif  // __TestModuleCommand
#include "DSYExport.h"
#endif //ExportedByTestModuleCommand_H

