//===================================================================
// COPYRIGHT  2022/03/08
//===================================================================
// CAAFirstCommand.cpp
// Header definition of class CAAFirstCommand
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2022/03/08 Creation: Code generated by the 3DS wizard
//===================================================================

#include "CAAFirstCommand.h"


#include "CATCreateExternalObject.h"
CATCreateClass( CAAFirstCommand);

//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
CAAFirstCommand::CAAFirstCommand() :
CATCommand (NULL, "CAAFirstCommand")
{
RequestStatusChange (CATCommandMsgRequestSharedMode);
}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
CAAFirstCommand::~CAAFirstCommand()
{
}


//  Overload this method: when your command gains focus
//
// Activates a command.
//   iFromClient :The command that requests to activate the current one.
//   iEvtDat :The notification sent.
// ----------------------------------------------------
CATStatusChangeRC CAAFirstCommand::Activate( CATCommand * iFromClient, CATNotification * iEvtDat)
{
return (CATStatusChangeRCCompleted);
}

//  Overload this method: when your command loses focus
//
// Deactivates a command.
//   iFromClient :The command that requests to activate the current one.
//   iEvtDat :The notification sent.
// ----------------------------------------------------
CATStatusChangeRC CAAFirstCommand::Desactivate( CATCommand * iFromClient, CATNotification * iEvtDat)
{
return (CATStatusChangeRCCompleted);
}

//  Overload this method: when your command is canceled
//
// Cancel a command.
//   iFromClient :The command that requests to activate the current one.
//   iEvtDat :The notification sent.
// ----------------------------------------------------
CATStatusChangeRC CAAFirstCommand::Cancel( CATCommand * iFromClient, CATNotification * iEvtDat)
{
RequestDelayedDestruction();
return (CATStatusChangeRCCompleted);
}
