//===================================================================
// COPYRIGHT  2022/03/08
//===================================================================
// CAASecondCommand.cpp
// Header definition of class CAASecondCommand
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2022/03/08 Creation: Code generated by the 3DS wizard
//===================================================================

#include "CAASecondCommand.h"

#include "CATCreateExternalObject.h"
CATCreateClass( CAASecondCommand);


//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
CAASecondCommand::CAASecondCommand() :
CATStateCommand ("CAASecondCommand", CATDlgEngOneShot, CATCommandModeShared)
//  Valid states are CATDlgEngOneShot and CATDlgEngRepeat
{
}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
CAASecondCommand::~CAASecondCommand()
{
}


//-------------------------------------------------------------------------
// BuildGraph()
//-------------------------------------------------------------------------
void CAASecondCommand::BuildGraph()
{


// TODO: Define the StateChart
// ---------------------------
}


//-------------------------------------------------------------------------
// ActionOne ()
//-------------------------------------------------------------------------
CATBoolean CAASecondCommand::ActionOne( void *data )
{
// TODO: Define the action associated with the transition
// ------------------------------------------------------

return TRUE;
}
