//===================================================================
// COPYRIGHT  2022/03/08
//===================================================================
// CAAThirdCommand.cpp
// Header definition of class CAAThirdCommand
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2022/03/08 Creation: Code generated by the 3DS wizard
//===================================================================

#include "CAAThirdCommand.h"
#include "CATIndicationAgent.h"

#include "CATCreateExternalObject.h"
CATCreateClass( CAAThirdCommand);


//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
CAAThirdCommand::CAAThirdCommand() :
CATStateCommand ("CAAThirdCommand", CATDlgEngOneShot, CATCommandModeShared)
//  Valid states are CATDlgEngOneShot and CATDlgEngRepeat
{
}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
CAAThirdCommand::~CAAThirdCommand()
{
}


//-------------------------------------------------------------------------
// BuildGraph()
//-------------------------------------------------------------------------
void CAAThirdCommand::BuildGraph()
{


// TODO: Define the StateChart
// ---------------------------
}


//-------------------------------------------------------------------------
// ActionOne ()
//-------------------------------------------------------------------------
CATBoolean CAAThirdCommand::ActionOne( void *data )
{
// TODO: Define the action associated with the transition
// ------------------------------------------------------

return TRUE;
}
