F_TestFramework=mkFrameworkCode "C:\Works\DS\Test\.\TestFramework" TestFramework - -
M_CATMecModLiveUseItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATMecModLiveUseItf\CATMecModLiveUseItf.m" CATMecModLiveUseItf - - - - - -
TRANSITIVEBUILT=NO
MKMK_DEVSTAGE=
MOD_LinkWith=M_JS0FM M_JS0GROUP M_JS0BASEILB M_CATSysMultiThreading M_CATSysTS M_CATSysTSObjectModeler M_DI0PANV2 M_CATDialogEngine M_CATMathematics M_CATAfrFoundation M_CATAfrItf M_CATVisItf M_CATAfrCompanion M_CATAfrComponentsModel M_CATGMGeometricInterfaces M_CATGeometricObjects M_CATAfrNavigator M_CATPartUseItf M_CATMecModUIUseItf M_CATMecModLiveUseItf M_CATSketcherUseItf M_CATSkt2DGeomIntegUseItf
MKMK_WARNING=
M_CAAPartDesignCommand=mkSharedLibrary "C:\Works\DS\Test\.\TestFramework\CAAPartDesignCommand.m" CAAPartDesignCommand - - - - - -
MKMK_ZIPJAVASOURCE=
M_CATGeometricObjects=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\GeometricObjects\CATGeometricObjects.m" CATGeometricObjects - - - - - -
GProtected=C:\Works\DS\Test\.\TestFramework\ProtectedGenerated\win_b64
IProtected=C:\Works\DS\Test\.\TestFramework\ProtectedInterfaces
M_CATVisItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\VisualizationInterfaces\CATVisItf.m" CATVisItf - - - - - -
MKMK_BSCMAKE=
M_CATSysTSObjectModeler=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\SystemTS\CATSysTSObjectModeler.m" CATSysTSObjectModeler - - - - - -
M_CATDialogEngine=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\DialogEngine\CATDialogEngine.m" CATDialogEngine - - - - - -
GLocal=C:\Works\DS\Test\.\TestFramework\CAAPartDesignCommand.m\LocalGenerated\win_b64
ILocal=C:\Works\DS\Test\.\TestFramework\CAAPartDesignCommand.m\LocalInterfaces
M_JS0BASEILB=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\SystemTS\JS0BASEILB.m" JS0BASEILB - - - - - -
IPublic=C:\Works\DS\Test\.\TestFramework\PublicInterfaces
GPublic=C:\Works\DS\Test\.\TestFramework\PublicGenerated\win_b64
MODSOURCES=C:\Works\DS\Test\.\TestFramework\CAAPartDesignCommand.m
MOD_INCPATH="C:\Works\DS\Test\.\TestFramework\CAAPartDesignCommand.m\src" "C:\Works\DS\Test\.\TestFramework\CAAPartDesignCommand.m\LocalInterfaces" "C:\Works\DS\Test\.\TestFramework\CAAPartDesignCommand.m\LocalGenerated\win_b64"
M_CATMathematics=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\Mathematics\CATMathematics.m" CATMathematics - - - - - -
GPrivate=C:\Works\DS\Test\.\TestFramework\PrivateGenerated\win_b64
IPrivate=C:\Works\DS\Test\.\TestFramework\PrivateInterfaces
USE_PDB_FILE=YES
WSPATH=C:\Works\DS\Test\.
M_CATAfrNavigator=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\AfrNavigator\CATAfrNavigator.m" CATAfrNavigator - - - - - -
MODPATH=C:\Works\DS\Test\.\TestFramework\CAAPartDesignCommand.m
FWNAME=TestFramework
WSROOT=C:\Works\DS\Test\.
CONTNAME=CAAPartDesignCommand
WSSOURCES=C:\Works\DS\Test\.
M_CATAfrComponentsModel=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\AfrComponentsModel\CATAfrComponentsModel.m" CATAfrComponentsModel - - - - - -
TARGETS_VALID=cppgrammar typelibgrammar compilation sourceruler cpponly link1st link2nd runtimedata buildtimedata
WSENAME_msg=TestFramework\CAAPartDesignCommand.m
MODDIRNAME=CAAPartDesignCommand.m
M_CATAfrCompanion=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\AfrFoundation\CATAfrCompanion.m" CATAfrCompanion - - - - - -
M_CATAfrFoundation=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\AfrFoundation\CATAfrFoundation.m" CATAfrFoundation - - - - - -
M_JS0GROUP=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\System\JS0GROUP.m" JS0GROUP - - - - - -
NAME=C:\Works\DS\Test\.\TestFramework\CAAPartDesignCommand.m\Objects\win_b64\.mkdata.mkb
M_CATSkt2DGeomIntegUseItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATSkt2DGeomIntegUseItf\CATSkt2DGeomIntegUseItf.m" CATSkt2DGeomIntegUseItf - - - - - -
M_CATAfrItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\AfrInterfaces\CATAfrItf.m" CATAfrItf - - - - - -
STEPS_TO_BUILD=DoxGrammar1st buildtimedata compilation cppgrammar cpponly cscimplement cscimplementclang grammar1st link1st link2nd runtimedata sourceruler typelibgrammar
WSEKEY=M_CAAPartDesignCommand
TARGET_DYNLINK=link1st link2nd
_MK_CLR_BLDCONF=MANAGED_CLR$(_MK_MSNET_VERS)
WIZARD_LINK_MODULES=JS0FM JS0GROUP DI0PANV2 CATDialogEngine CATMathematics CATAfrFoundation CATGMGeometricInterfaces CATGeometricObjects CATAfrNavigator CATPartUseItf CATMecModUIUseItf CATVisItf CATMecModLiveUseItf CATSketcherUseItf
WSSOURCES_Concat="C:\Works\DS\Test\." "C:\Program Files\Dassault Systemes\B422\."
M_DI0PANV2=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\Dialog\DI0PANV2.m" DI0PANV2 - - - - - -
FW_AllPreq=AfrFoundation,21ED1151;AfrInterfaces,21ED1151;AfrNavigator,21EE1151;BSFBuildtimeData,21DD1140;CATImmPPRNavInterfaces,21EE1151;CATMecModLiveUseItf,21EE1151;CATMecModUIUseItf,21EE1151;CATPartUseItf,21EE1151;CATSketcherUseItf,21EE1151;DELPPRAuthFoundationInterfaces,21EE1151;DELPPRLiveSystemUseItf,21EE1151;Dialog,21EC1151;DialogEngine,21ED1151;GeometricObjects,21ED1151;Mathematics,21ED1151;SpecialAPI,21ED1151;System,21ED1151;VisualizationInterfaces,21ED1151;AdvancedMathematics,20DD1151;AfrComponentsModel,20CC1141;CATGSMUseItf,20EE1151;CATMathStream,20DD1151;CATMecModUseItf,20EE1151;CATPLMComponentInterfaces,20EE1151;CATPLMIdentificationAccess,20CC1151;CATSkt2DGeomIntegUseItf,20EE1151;CATStyleProcessor,20DD1141;CATView,20DD1151;CATVirtualVaultSystem,20DD1151;DataCommonProtocolUse,20DD1131;GMModelInterfaces,20EE1151;Graph,20DD1151;IVInterfaces,20DD1151;InfInterfaces,20DD1151;InfOSIDLItf,20DD1151;InteractiveInterfaces,20DD1131;IntrospectionInfrastructure,20CC1141;KnowledgeInterfaces,20DD1151;MultimediaInterfaces,20DD1151;MultimediaPixelImage,20DD1151;OOCInterfaces,20CC1141;ObjectModelerBase,20DD1151;ObjectModelerCollection,20DD1131;ObjectModelerEngines,20CC1151;ObjectModelerInterfaces,20DD1151;ObjectModelerNavigator,20DD1151;ObjectModelerSystem,20DD1151;PLMDictionaryInterfaces,20DD1151;SGCoreUtils,20CC1141;SGInfra,20CC1151;SGManager,20CC1151;SystemTS,20CC1131;UIVCoreTools,20DD1131;VisuImmersiveDialog,20CC1151;VisuImmersiveDialogEx,20DD1151;VisuImmersiveUI,20DD1151;VisualizationController,20DD1151;VisualizationCore,20CC1151;VisualizationFoundation,20CC1151;VisualizationSceneGraph,20CC1151;XMLParserItf,20DD1151;
FWCOMPANYNAME=
M_CATMecModUIUseItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATMecModUIUseItf\CATMecModUIUseItf.m" CATMecModUIUseItf - - - - - -
BUILD=YES
MOD_Container=CAAPartDesignCommand.m
WS_Concat="C:\Works\DS\Test\." "C:\Program Files\Dassault Systemes\B422\."
FWmkHLpath=C:\Works\DS\Test\.\TestFramework\IdentityCard\Objects\win_b64\.mkHLpath.mk
M_CATGMGeometricInterfaces=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\GeometricObjects\CATGMGeometricInterfaces.m" CATGMGeometricInterfaces - - - - - -
MOD_ObjectsPath=C:\Works\DS\Test\.\TestFramework\CAAPartDesignCommand.m\Objects\win_b64
M_CATPartUseItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATPartUseItf\CATPartUseItf.m" CATPartUseItf - - - - - -
RTViewDataListPath=C:\Works\DS\Test\.\TestFramework\various\win_b64\CAAPartDesignCommand.m\module.data
M_JS0FM=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\System\JS0FM.m" JS0FM - - - - - -
FWCOPYRIGHT=
TYPELATE=mkSharedLibrary
BUILT_OBJECT_TYPE=SHARED LIBRARY
IMAKEKEY_VALID=COMDYN_MODULE INCLUDED_MODULES
TARGETS_MANDATORY=cscimplement cscimplementclang
FW_INCPATH="C:\Works\DS\Test\.\TestFramework\PrivateInterfaces" "C:\Works\DS\Test\.\TestFramework\PrivateGenerated\win_b64" "C:\Works\DS\Test\.\TestFramework\ProtectedInterfaces" "C:\Works\DS\Test\.\TestFramework\ProtectedGenerated\win_b64" "C:\Works\DS\Test\.\TestFramework\PublicInterfaces" "C:\Works\DS\Test\.\TestFramework\PublicGenerated\win_b64"
MOD_SrcPath=C:\Works\DS\Test\.\TestFramework\CAAPartDesignCommand.m\src
DOC_RTViewDataListPath=C:\Works\DS\Test\.\TestFramework\various\win_b64.doc\CAAPartDesignCommand.m\module.data
LINK_WITH=JS0FM JS0GROUP DI0PANV2 CATDialogEngine CATMathematics CATAfrFoundation CATGMGeometricInterfaces CATGeometricObjects CATAfrNavigator CATPartUseItf CATMecModUIUseItf CATVisItf CATMecModLiveUseItf CATSketcherUseItf
MOD_Included=M_CAAPartDesignCommand
M_CATSysTS=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\SystemTS\CATSysTS.m" CATSysTS - - - - - -
FWPATH=C:\Works\DS\Test\.\TestFramework
MK_BUILD_CONFIGURATION=
MKMK_DEBUG=YES
FWSOURCES=C:\Works\DS\Test\.\TestFramework
M_CATSketcherUseItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATSketcherUseItf\CATSketcherUseItf.m" CATSketcherUseItf - - - - - -
STEPS_TO_CLEAN=
M_CATSysMultiThreading=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\SystemTS\CATSysMultiThreading.m" CATSysMultiThreading - - - - - -
MKMK_DEBUGEDITANDCONTINUE=
FWDNAME=TestFramework
MODNAME=CAAPartDesignCommand
REAL_LINK_WITH=JS0FM JS0GROUP JS0BASEILB CATSysMultiThreading CATSysTS CATSysTSObjectModeler DI0PANV2 CATDialogEngine CATMathematics CATAfrFoundation CATAfrItf CATVisItf CATAfrCompanion CATAfrComponentsModel CATGMGeometricInterfaces CATGeometricObjects CATAfrNavigator CATPartUseItf CATMecModUIUseItf CATMecModLiveUseItf CATSketcherUseItf CATSkt2DGeomIntegUseItf
