// COPYRIGHT DASSAULT SYSTEMES 2009
#======================================================================
# Imakefile for module TestModule
#======================================================================
#  2022/03/07 Creation: Code generated by the 3DS wizard
#======================================================================
#

BUILT_OBJECT_TYPE=SHARED LIBRARY

#INSERTION ZONE NOT FOUND, MOVE AND APPEND THIS VARIABLE IN YOUR LINK STATEMENT
LINK_WITH = $(WIZARD_LINK_MODULES)
# DO NOT EDIT :: 3DS WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = JS0FM   \
JS0GROUP \
DELPPRAuthFoundationItf \
CATAfrItf \
CATAfrFoundation \
CATMecModUIUseItf \
CATImmPPRNavInterfaces \
DELPPRLiveSystemUseItfCPP \

# END WIZARD EDITION ZONE
