//===================================================================
// COPYRIGHT  2022/03/07
//===================================================================
// CAAComponentAddin.cpp
// Header definition of class CAAComponentAddin
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2022/03/07 Creation: Code generated by the 3DS wizard
//===================================================================

#include "CAAComponentAddin.h"

CATImplementClass(CAAComponentAddin,Implementation,CATBaseUnknown,CATNull);

// #include "TIE_CATIAfrGeneralWksAddin.h"
// TIE_CATIAfrGeneralWksAddin(CAAComponentAddin);

// Process Planning
#include "TIE_CATIManufacturingSystemDefinitionWorkbenchAddin.h"
TIE_CATIManufacturingSystemDefinitionWorkbenchAddin(CAAComponentAddin);

//-----------------------------------------------------------------------------
// CAAComponentAddin : constructor
//-----------------------------------------------------------------------------
CAAComponentAddin::CAAComponentAddin():CATBaseUnknown()
{
//
//TODO: Add the constructor code here
//
}

//-----------------------------------------------------------------------------
// CAAComponentAddin : destructor
//-----------------------------------------------------------------------------
CAAComponentAddin::~CAAComponentAddin()
{
//
// TODO: Place code here.
//
}


void CAAComponentAddin::CreateCommands()
{

	CATAfrCommandHeader::CATCreateCommandHeader("CAAAfrUnionHdr",	// resource file. like *** CAAComponentAddin.CAAAfrUnionHdr.Title = "Union" ;
		"TestModuleCommand",										// Module name
		"CAAFirstCommand",											// command class name of module
		(void *)NULL, 
		"CAAComponentAddin",										// resource file name
		CATFrmAvailable);

	CATAfrCommandHeader::CATCreateCommandHeader("CAAAfrSubstractHdr", "TestModuleCommand", "CAASecondCommand", (void *)NULL, "CAAComponentAddin", CATFrmAvailable);

	CATAfrCommandHeader::CATCreateCommandHeader("CAAAfrFilletHdr", "TestModuleCommand", "CAAThirdCommand", (void *)NULL, "CAAComponentAddin", CATFrmAvailable);

}

CATCmdContainer *CAAComponentAddin::CreateToolbars()
{
	NewAccess(CATCmdContainer, pCAAAfrOperationTlb, CAAAfrOperationTlb);

	//Insert in the CAA Geometry Creation section
	// third CAAComponentAddinSection == section in Resource file
	NewAccess(CATCmdContainer, pCAAComponentAddinSection, CAAComponentAddinSection);
	AddAccessChild(pCAAComponentAddinSection, pCAAAfrOperationTlb);

	//////////////////////////////////////////////////////////////////////////
	NewAccess(CATCmdStarter, pCAAAfrTUnionStr, CAAAfrTUnionStr);
	SetAccessCommand(pCAAAfrTUnionStr, "CAAAfrUnionHdr");
	SetAccessChild(pCAAAfrOperationTlb, pCAAAfrTUnionStr);

	NewAccess(CATCmdStarter, pCAAAfrTSubstractStr, CAAAfrTSubstractStr);
	SetAccessCommand(pCAAAfrTSubstractStr, "CAAAfrSubstractHdr");
	SetAccessNext(pCAAAfrTUnionStr, pCAAAfrTSubstractStr);

	NewAccess(CATCmdStarter, pCAAAfrTFilletStr, CAAAfrTFilletStr);
	SetAccessCommand(pCAAAfrTFilletStr, "CAAAfrFilletHdr");
	SetAccessNext(pCAAAfrTSubstractStr, pCAAAfrTFilletStr);
	//////////////////////////////////////////////////////////////////////////

	return pCAAComponentAddinSection;
}







