//===================================================================
// COPYRIGHT  2022/03/08
//===================================================================
// CAAPartDesignAddin.cpp
// Header definition of class CAAPartDesignAddin
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2022/03/08 Creation: Code generated by the 3DS wizard
//===================================================================

#include "CAAPartDesignAddin.h"

CATImplementClass(CAAPartDesignAddin,Implementation,CATBaseUnknown,CATNull);

// Part Design
#include "TIE_CATIPrtWksAddin.h"
TIE_CATIPrtWksAddin(CAAPartDesignAddin);


//-----------------------------------------------------------------------------
// CAAPartDesignAddin : constructor
//-----------------------------------------------------------------------------
CAAPartDesignAddin::CAAPartDesignAddin():CATBaseUnknown()
{
//
//TODO: Add the constructor code here
//
}

//-----------------------------------------------------------------------------
// CAAPartDesignAddin : destructor
//-----------------------------------------------------------------------------
CAAPartDesignAddin::~CAAPartDesignAddin()
{
//
// TODO: Place code here.
//
}

void CAAPartDesignAddin::CreateCommands()
{
	CATAfrCommandHeader::CATCreateCommandHeader("CAAAfrPointHdr",
		"CAAPartDesignCommand",
		"CAADegCreatePointCmd",
		(void *)NULL,
		"CAAPartDesignAddin",
		CATFrmAvailable);

	CATAfrCommandHeader::CATCreateCommandHeader("CAADegEditSketchHdr", "CAAPartDesignCommand", "CAADegEditSketchCmd", (void *)NULL, "CAAPartDesignAddin", CATFrmAvailable);
}

CATCmdContainer * CAAPartDesignAddin::CreateToolbars()
{
	NewAccess(CATCmdContainer, pCAAPartDesignTlb, CAAPartDesignTlb);

	//Insert in the CAA Geometry Creation section
	// third CAAComponentAddinSection == section in Resource file
	NewAccess(CATCmdContainer, pCAAPartDesignAddinSection, CAAPartDesignAddinSection);
	AddAccessChild(pCAAPartDesignAddinSection, pCAAPartDesignTlb);


	NewAccess(CATCmdStarter, pCAADegCreatePointStr, CAADegCreatePointStr);
	SetAccessCommand(pCAADegCreatePointStr, "CAAAfrPointHdr");
	SetAccessChild(pCAAPartDesignTlb, pCAADegCreatePointStr);

	NewAccess(CATCmdStarter, pCAADegEditSketchStr, CAADegEditSketchStr);
	SetAccessCommand(pCAADegEditSketchStr, "CAADegEditSketchHdr");
	SetAccessNext(pCAADegCreatePointStr, pCAADegEditSketchStr);


	return pCAAPartDesignAddinSection;
}








