// COPYRIGHT DASSAULT SYSTEMES 2009
#======================================================================
# Imakefile for module CAAPartDesignCommand
#======================================================================
#  2022/03/08 Creation: Code generated by the 3DS wizard
#======================================================================
#

BUILT_OBJECT_TYPE=SHARED LIBRARY

#INSERTION ZONE NOT FOUND, MOVE AND APPEND THIS VARIABLE IN YOUR LINK STATEMENT
LINK_WITH = $(WIZARD_LINK_MODULES)
# DO NOT EDIT :: 3DS WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = JS0FM   \
JS0GROUP \
DI0PANV2 \
CATDialogEngine \
CATMathematics \
CATAfrFoundation \
CATGMGeometricInterfaces \
CATGeometricObjects \
CATAfrNavigator \
CATPartUseItf \
CATMecModUIUseItf \
CATVisItf \
CATMecModLiveUseItf \
CATSketcherUseItf \
# END WIZARD EDITION ZONE
