
//===================================================================
// COPYRIGHT  2022/03/08
//===================================================================
// CAAPartDesignAddin.cpp
// Header definition of class CAAPartDesignAddin
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2022/03/08 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef CAAPartDesignAddin_H
#define CAAPartDesignAddin_H

#include "CATBaseUnknown.h"
class CATCmdContainer;

#include "CATCreateWorkshop.h"
#include "CATAfrCommandHeader.h"

#include "CATIPrtWksAddin.h"
//-----------------------------------------------------------------------

class CAAPartDesignAddin: public CATBaseUnknown

{
CATDeclareClass;

public:

// Standard constructors and destructors
// -------------------------------------
CAAPartDesignAddin ();
virtual ~CAAPartDesignAddin ();

//
// TODO: Add your methods for this class here.
//
void CreateCommands();
CATCmdContainer *CreateToolbars();



private:
// Copy constructor and equal operator
// -----------------------------------
CAAPartDesignAddin (CAAPartDesignAddin &);
CAAPartDesignAddin& operator=(CAAPartDesignAddin&);
};

//-----------------------------------------------------------------------

#endif

